#!/bin/bash

# Script to generate separate export files for each icon pack
# This improves IDE performance and provides better organization

echo "🔄 Generating separate export files for each icon pack..."

cd "$(dirname "$0")/.." || exit 1

# Create temporary directory for grouping icons
mkdir -p src/packs

# Get all unique prefixes (first 2 characters)
PREFIXES=$(find src/icons -name "*.tsx" -type f | \
  sed 's|src/icons/||' | \
  cut -c1-2 | \
  sort -u)

# Generate export file for each prefix
for PREFIX in $PREFIXES; do
  PREFIX_LOWER=$(echo "$PREFIX" | tr '[:upper:]' '[:lower:]')
  PACK_FILE="src/packs/${PREFIX_LOWER}.tsx"
  
  echo "// Auto-generated exports for ${PREFIX} icon pack" > "$PACK_FILE"
  echo "// This file is generated by scripts/generate-exports.sh" >> "$PACK_FILE"
  echo "" >> "$PACK_FILE"
  
  # Find all icons with this prefix and export them
  find src/icons -name "${PREFIX}*.tsx" -type f | \
    sed 's|src/icons/||' | \
    sed 's|.tsx$||' | \
    sort | \
    awk '{printf "export { default as %s } from '\''../icons/%s'\'';\n", $1, $1}' >> "$PACK_FILE"
  
  ICON_COUNT=$(grep -c "export" "$PACK_FILE")
  echo "✅ Generated ${PREFIX_LOWER}.tsx with $ICON_COUNT icons"
done

# Generate main index.tsx that re-exports everything (for backward compatibility)
echo "🔄 Generating main src/index.tsx..."

echo "// Auto-generated main export file" > src/index.tsx
echo "// For better IDE performance, consider importing from specific packs:" >> src/index.tsx
echo "// import { AiFillHeart } from 'react-native-icons-svg/ai';" >> src/index.tsx
echo "" >> src/index.tsx

# Re-export from all pack files
for PREFIX in $PREFIXES; do
  PREFIX_LOWER=$(echo "$PREFIX" | tr '[:upper:]' '[:lower:]')
  echo "export * from './packs/${PREFIX_LOWER}';" >> src/index.tsx
done

# Add utility exports
echo "" >> src/index.tsx
echo "// Utility exports" >> src/index.tsx
echo "export { GenIcon } from './utils';" >> src/index.tsx

# Count total icons
TOTAL_ICONS=$(find src/icons -name "*.tsx" -type f | wc -l)
TOTAL_PACKS=$(echo "$PREFIXES" | wc -l)

echo ""
echo "✅ Generation complete!"
echo "📊 Total: $TOTAL_ICONS icons in $TOTAL_PACKS packs"
echo "📦 Tree-shaking enabled for all exports"
echo ""
echo "💡 Usage examples:"
echo "   import { AiFillHeart } from 'react-native-icons-svg/ai';  // Faster IDE"
echo "   import { AiFillHeart } from 'react-native-icons-svg';      // Still works"
echo ""

